// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.baseweb;

import com.baseweb.UserDao;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserDao_Roo_Configurable {
    
    declare @type: UserDao: @Configurable;
    
}
